services:
  postgres_db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "users"

  redis_db:
    image: redis:latest
    ports:
      - "6379:6379"