// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Role struct {
	ID    uuid.UUID
	Name  string
	Level int32
}

type User struct {
	ID       uuid.UUID
	Username string
	Password []byte
	Email    string
	Createat time.Time
}

type UserRole struct {
	UserID uuid.UUID
	RoleID uuid.UUID
}
